#!/usr/bin/env bash
#display
c=1
while [ "$c" -le 10 ]
do 
	if [ "$c" -eq 4 ]
	then
		echo "bad luck"
	if [ "$c" -eq 8 ]
        then
		echo "good luck"
	else 
		echo "Best School"
	fi
	((c++))
done	
