#!/usr/bin/env bash
#Displays Y U no love me?! when receiving a SIGINT signal
PID_FILE="/var/run/myscript.pid"
echo $$ > "$PID_FILE"
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -f "$PID_FILE"; exit 0' SIGTERM

trap 'rm -f "$PID_FILE"; exit 0' SIGQUIT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
