#!/usr/bin/env bash
#Displays Y U no love me?! when receiving a SIGINT signal
echo "$$" > /tmp/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
