#!/usr/bin/env bash
#a Bash script that displays the PID, along with the process name, of processes whose name contain the word bash
for pid in /proc/[0-9]*; do
    name=$(cat "$pid/comm" 2>/dev/null)
    if echo "$name" | grep -q "bash"; then
        echo "$(basename "$pid") $name"
    fi
done
